### ISSUE TITLE
Unable to run examples

### ISSUE THREAD

**Issue by arshadsurti** [playwright-community/playwright-jest-examples#12]
Downloaded the repo, done an npm install, and ran npm run tests... get the following error message...

> Executing task: npm run test <

> jest-playwright-example-basic-ts@1.0.0 test C:\sandbox\playwright-jest-examples\basic-ts
> jest

C:\sandbox\playwright-jest-examples\basic-ts\node_modules\jest-playwright-preset\node_modules\uuid\dist\esm-browser\index.js:1
export { default as v1 } from './v1.js';
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1043:16)
    at Module._compile (internal/modules/cjs/loader.js:1091:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1160:10)
    at Module.load (internal/modules/cjs/loader.js:976:32)
    at Function.Module._load (internal/modules/cjs/loader.js:884:14)
    at Module.require (internal/modules/cjs/loader.js:1016:19)
    at require (internal/modules/cjs/helpers.js:69:18)
    at Object.<anonymous> (C:\sandbox\playwright-jest-examples\basic-ts\node_modules\jest-playwright-preset\lib\coverage.js:26:27)
    at Module._compile (internal/modules/cjs/loader.js:1121:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1160:10)

Test Suites: 0 of 4 total
Tests:       0 total
Snapshots:   0 total
Time:        0 snpm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jest-playwright-example-basic-ts@1.0.0 test: `jest`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jest-playwright-example-basic-ts@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\arshadsurti\AppData\Roaming\npm-cache\_logs\2020-07-15T09_35_22_271Z-debug.log
The terminal process terminated with exit code: 1

**Comment by mxschmitt** [comment]
Which Node.js version do you have?

**Comment by arshadsurti** [comment]
Thanks for the quick response @mxschmitt  my PC is running node v13.2.0 which is didnt work on, I've just tried on my laptop running node v12.16.1 and it works fine

**Comment by mxschmitt** [comment]
I've created an upstream issue https://github.com/playwright-community/jest-playwright/pull/225 to see if it's still reproducible. Let's see if this is an actual bug or maybe already fixed in Node.js.

Thanks for reporting!

**Comment by mxschmitt** [comment]
Small update, I tried it on 12.x 13.x and 14.x and all the runs were successful: https://github.com/playwright-community/playwright-jest-examples/pull/14/checks?check_run_id=873140593

Let me know if you experience any other issues.
